app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
  path: /login
  defaults: { _controller: AppBundle:Default:login }

login_check:
  path: /login_check

logout:
  path: /logout


administradorPage:
  path: /administradorPage
  defaults: { _controller: AppBundle:Administrador:index }

tesoreroPage:
  path: /tesoreroPage
  defaults: { _controller: AppBundle:Tesorero:index }

obreroPage:
  path: /obreroPage
  defaults: { _controller: AppBundle:Tesorero:index }

usuarios:
  path: /usuarios
  defaults: { _controller: AppBundle:Administrador:usuarios }

nuevoUsuario:
  path: /nuevoUsuario
  defaults: { _controller: AppBundle:Administrador:nuevoUsuario }

editarUsuario:
  path: /editarUsuario/{id}
  defaults: { _controller: AppBundle:Administrador:editarUsuario}

miembros:
  path: /miembros
  defaults: { _controller: AppBundle:Administrador:miembros }

detalleMiembro:
  path: /detalleMiembro/{id}
  defaults: { _controller: AppBundle:Administrador:detalleMiembro }

nuevoMiembro:
  path: /nuevoMiembro
  defaults: { _controller: AppBundle:Administrador:nuevoMiembro }

editarMiembro:
  path: /editarMiembro{id}
  defaults: { _controller: AppBundle:Administrador:editarMiembro }

presentacion:
  path: /presentacion
  defaults: {_controller: AppBundle:Administrador:presentacion }

nuevaPresentacion:
  path: /nuevaPresentacion
  defaults: {_controller: AppBundle:Administrador:nuevaPresentacion }

bautizados:
  path: /bautizados
  defaults: {_controller: AppBundle:Administrador:bautizados}

seleccionarMiembro:
  path: /seleccionarMiembro
  defaults: {_controller: AppBundle:Administrador:seleccionarMiembro}

nuevoBautizo:
  path: /nuevoBautizo
  defaults: {_controller: AppBundle:Administrador:nuevoBautizo}

ministerio:
  path: /ministerio
  defaults: { _controller: AppBundle:Administrador:ministerio }

nuevoMinisterio:
  path: /nuevoMinisterio
  defaults: {_controller: AppBundle:Administrador:nuevoMinisterio} 

detallesMinisterio:
  path: /detallesMinisterio/{id}
  defaults: { _controller: AppBundle:Administrador:detallesMinisterio }

asignarMiembroMinisterio:
  path: /asignarMiembro/{idm}
  defaults: { _controller: AppBundle:Administrador:asignarMiembroMinisterio }

borrarMiembroMinisterio:
  path: /borrarMiembroMinisterio/{id}
  defaults: { _controller: AppBundle:Administrador:borrarMiembroMinisterio }

asignacionMiembroMinisterio:
  path: /asignacionMiembroMinisterio/{id}/{idm}
  defaults: { _controller: AppBundle:Administrador:asignacionMiembroMinisterio }

asignacionLiderMinisterio:
 path: /asignacionLiderMinisterio/{id}/{idm}
 defaults: {_controller: AppBundle:Administrador:asignacionLiderMinisterio }

asignarLider:
  path: /asignarLider/{id}
  defaults: { _controller: AppBundle:Administrador:asignarLider }

cambioLiderMinisterio:
  path: /cambioLiderMinisterio/{id}
  defaults: {_controller: AppBundle:Administrador:cambioLiderMiembro}



tesoreriaAdministrador:
  path: /tesoreriaAdministrador
  defaults: { _controller: AppBundle:Administrador:tesoreriaAdministrador }

nuevaTransaccion:
  path: /nuevaTransaccion
  defaults: { _controller: AppBundle:Administrador:nuevaTransaccion }


nuevoTipotransaccion:
  path: /nuevoTipotransaccion
  defaults: { _controller: AppBundle:Administrador:nuevoTipotransaccion }

reportesAdministrador:
  path: /reportesAdministrador
  defaults: { _controller: AppBundle:Administrador:reportesAdministrador }

pdfMinisterio:
  path: /pdfMinisterio/{id}
  defaults: { _controller: AppBundle:Administrador:pdfMinisterio }